# Generated by Django 5.2.4 on 2025-12-28 06:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_service_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for this service', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
