# Generated by Django 4.2.14 on 2025-12-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_purchaseinvoice_paid_amount_service_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before tax', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage applied', max_digits=5),
        ),
    ]
