# Generated by Django 4.2.14 on 2025-12-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_sale_subtotal_sale_tax_amount_sale_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Bill number from supplier (e.g., 0001, 0002, or custom like ABC-001)', max_length=50, null=True),
        ),
    ]
