# Generated by Django 5.2.4 on 2025-12-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_purchase_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, help_text='Auto-generated full invoice number', max_length=100),
        ),
    ]
