# Generated by Django 5.2.4 on 2025-12-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_alter_purchase_supplier_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
        ),
    ]
