# Generated by Django 5.2.4 on 2025-12-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_remove_purchaseinvoice_supplier_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, help_text='Supplier invoice number', max_length=100),
        ),
    ]
