# Generated by Django 4.2.14 on 2026-01-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_purchaseinvoice_supplier_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_date',
        ),
    ]
