# Generated by Django 5.2.4 on 2026-01-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_remove_order_estimated_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cut_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
