# Generated by Django 5.2.4 on 2026-01-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_product_cut_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='bill_number',
        ),
    ]
