# Generated by Django 5.2.4 on 2026-01-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_remove_purchase_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Bill number from supplier (e.g., 0001, 0002, or custom like ABC-001)', max_length=50, null=True),
        ),
    ]
