# Generated by Django 5.2.4 on 2026-01-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_purchase_bill_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
